### ISSUE TITLE
Preserve time stamp

### ISSUE THREAD

**Issue by eldelacajita** [Huluti/Curtail#103]
I'm using Curtail a lot lately and I love it. 

However, one thing that breaks my workflow and file management is that optimizing the image updates its time stamp, so I can't rely anymore on that parameter for searching, filtering or organizing my images by date. The time I optimized a picture is usually not relevant at all for that, while the time it was taken or created is.

Could Curtail implement something that copies or keeps the original time stamp?
I think this should be the default, but if there are some use cases for having the date updated, then this could become an option.

**Comment by eldelacajita** [comment]
I've been using the `touch -r` command but just found out that jpegoptim has a `-p` (preserve) parameter that keeps the timestamp. I think optipng has a similar one.

It shouldn't be very difficult to implement this, either as a default behavior (at least when set to overwrite the original files) or as a setting... or even linked to the "preserve metadata" setting.

**Comment by Huluti** [comment]
Yes thank you for the suggestion, I'm working on this right now. Should be released very soon :)

**Comment by eldelacajita** [comment]
Awesome! Looking forward to it.
