### ISSUE TITLE
question about po/fr, gnome software and french translation

### ISSUE THREAD

**Issue by BirdInFire** [Huluti/Curtail#107]
Hello,
I actually want to know one thing, gnome software (flatpak (1.2.2)) say it's only english since french isn't here, but in po file i see french, can you help me (to fix / finish) the translation by explaining where i can find what this file miss to actually work (i will translate what the file miss).

Thanks

**Comment by Huluti** [comment]
Hello :)
Yes a French translation is available but I don't know why gnome software think not. Let met check that and I'll say you if I need your help. Thanks!

**Comment by BirdInFire** [comment]
> Hello! Yes a French translation is available but I don't know why gnome software think not. Let met check that and I'll say you if I need your help. Thanks!

no problem, maybe the manifest file, i have tested it and it switch to french but the warning bar of gnome-software remain saying it will be in English.

**Comment by Huluti** [comment]
Fixed! It was the translation percentage being < 50%.
