### ISSUE TITLE
Switch to oxipng instead of OptiPNG

### ISSUE THREAD

**Issue by kah0922** [Huluti/Curtail#108]
OptiPNG is slow and hasn't seen a release since 2017. Oxipng is faster, multi-threaded, still receives updates, and has better compression in my experience.

**Comment by Huluti** [comment]
Wasn't aware of this library. Thanks for the info, I'll try to do some tests and see if it could be a better option for Curtail.

**Comment by RDKRACZ** [comment]
I would also recommend checking Leanify, it's even better.
