### ISSUE TITLE
Better appstream screenshots

### ISSUE THREAD

**Issue by bertob** [Huluti/Curtail#118]
The current screenshots don't look that good, in part because they don't follow the [guidelines](https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/Update-App-Screenshots) in a number of ways, including
- No baked-in shadow
- Too many window controls (should be just close)
- Old version of some of the icons

![image](https://user-images.githubusercontent.com/1908896/173551211-ba14b278-816d-4212-bb85-ad0ad57836e1.png)

Of course probably the main thing needed to *really* make the screenshots look great is an update to GTK4, but that's a separate issue :)

**Comment by Huluti** [comment]
Totally agree! Thanks for the issue :)
