### ISSUE TITLE
Odd empty state layout

### ISSUE THREAD

**Issue by bertob** [Huluti/Curtail#119]
The empty state is a bit odd visually, I think primarily because
- The hierarchy is unclear, there isn't a single thing to focus on first, or path for the eye to move
- The layout is very different from other apps do
- The switch with two labels with different text styling feels off
- The disabled back/forward buttons are superfluous

![image](https://user-images.githubusercontent.com/1908896/173552595-00f66c28-3c12-4924-b3a3-de9483b09686.png)

A few tips for a better layout:
- Drop subtitle in the headerbar and make it a statuspage header instead
- Add a statuspage icon (probably the app icon or symbolic)
- Add a description explaining the 
- Make the file picker a suggested pill button
- Drop the text styling on the Lossy/Lossless labels
- Drop the back/forward buttons

**Comment by Huluti** [comment]
Most of suggestions taken in #138 and next steps in #139
