### ISSUE TITLE
Use Hdy/AdwPreferences widgets

### ISSUE THREAD

**Issue by bertob** [Huluti/Curtail#120]
The preferences window would benefit from using the standard Hdy/Adw preferences widgets instead of something custom, primarily because it'd match the rest of the system in terms of listbox style, would be adaptive, and get search for free.

![image](https://user-images.githubusercontent.com/1908896/173555546-d19bdc83-39ab-45a8-adef-ae96c53ed0fa.png)

**Comment by Huluti** [comment]
Done in #138
