### ISSUE TITLE
fedora copr

### ISSUE THREAD

**Issue by 0xMRTT** [Huluti/Curtail#127]
I've created a copr for curtail

https://copr.fedorainfracloud.org/coprs/0xmrtt/curtail/

You can install curtail using

```
dnf copr enable 0xmrtt/curtail
dnf in curtail 
```

**Comment by Huluti** [comment]
Woah good news! Thanks for that. I'll add these lines on readme instructions soon :)

**Comment by Huluti** [comment]
Included in the README :) Thanks again!
