### ISSUE TITLE
Too slow while compress image in the phone

### ISSUE THREAD

**Issue by TIIEHenry** [Huluti/Curtail#131]
When I compress a picture on my phone, I want it to be processed in the computer's cache, not on my phone

**Comment by Huluti** [comment]
Can you explain more? I don't undestand your use case. You have a Linux Phone with Curtail on it?

**Comment by TIIEHenry** [comment]
an android phone and ubuntu pc, process pictures in my phone

**Comment by Huluti** [comment]
Could you please retry with the latest version (1.6.0)? Thanks!

**Comment by Huluti** [comment]
Closing it for now. Don't hesitate to reopen if needed.
