### ISSUE TITLE
 Odd empty state layout followup

### ISSUE THREAD

**Issue by Huluti** [Huluti/Curtail#139]
A few more things I noticed:

- [x] The view with the file list is a treeview, and feels cramped and not very legible. Given the amount of information we're displaying here (just filename + 3 pieces of metadata) I think a listbox would be a much better fit here, maybe with file name as the title, the two different sizes as subtitle, and the savings in green/red on the right side of the row. Switching to list rows would also have the advantage that the rows would be taller, which would allow for image thumbnails, which would really help to know which image is which at a glance.
- [x] It's not clear to me what exactly the back/forward buttons are for. They seem to just go back to the empty state after you've converted some files? If so, I don't think this is the best pattern for this, I'd go with something like a "clear" button instead (e.g. in the primary menu).
- [x] There's a "browse" button on the welcome view but not after that. I'd have an open button in the top left, or a floating pill button in the bottom center for that.
- The layout of the welcome view feels a bit messy, there are lots of elements with different sizes and shapes. Some suggestions:
  - [x] Use a standard status page layout with the app icon at the top
  - [x] Move the open button to the top left, or make it a floating pill button
  - [ ] The lossless/lossy switch is a bit odd, and IMO the options could use a bit more context. Perhaps two radio button rows would work here, then we could also have a subtitle for each to explain the options?
  - [x] "Images are saved with -min prefix" could perhaps be integrated in the description

_Originally posted by @bertob in https://github.com/Huluti/Curtail/issues/138#issuecomment-1479811779_

**Comment by Huluti** [comment]
![image](https://user-images.githubusercontent.com/5782198/229134363-de9d4756-407a-4d27-b3d2-6e071fc467cf.png)

@bertob any thought on this? thanks :)

**Comment by bertob** [comment]
Definitely an improvement, though I wouldn't drop the reference to DnD. Maybe "Drop images here to compress them" as the subtitle?

**Comment by Huluti** [comment]
![image](https://user-images.githubusercontent.com/5782198/229381518-40a7b4a2-070e-4895-bbe0-b529c258e61c.png)

Yes right, it's an useful info. But no more indication on the program pupose?

**Comment by bertob** [comment]
The string I proposed above does both. I'd definitely not do an ellipsis here though, it's unnecessary.

**Comment by Huluti** [comment]
@bertob with all recent updates, do you still think that the "Lossless/Lossy" can be improved?
Don't really image how you visualise the radio buttons here :) Thanks!

**Comment by bertob** [comment]
Yeah, all else being equal I don't think making them radio rows would work here. I guess the status quo is maybe fine now that the rest of the view has been cleaned up.

**Comment by akozlovskiy119** [comment]
Ideally, the lossless/lossy switch should be replaced by a quality slider so that 100% means lossless and everything below means lossy. The slider should receive information from the compressor about compression values and increment steps that are available for the image type, or, if the options are not available, should be hidden.
