### ISSUE TITLE
Listbox is the full height of the window

### ISSUE THREAD

**Issue by bertob** [Huluti/Curtail#146]
Listboxes should only be as large as the content, i.e. just one row tall in this case.

![image](https://user-images.githubusercontent.com/1908896/229379713-1e97d883-613e-49d7-b55b-846174623fff.png)

**Comment by Huluti** [comment]
@A6GibKm Hello! can't find a way to have the scrolledwindow follow the growth of the listbox. Myabe you could have an idea?

**Comment by A6GibKm** [comment]
This prob means that the list box has valign set to something other than start

**Comment by bertob** [comment]
Another connected issue: The scrollbar should be on the view, not on the content (i.e. all the way on the edge). There shouldn't be padding around the scrollview (see the cut-off content at the top and bottom).

![image](https://user-images.githubusercontent.com/1908896/229483105-12f1ff65-f57b-4611-b5fc-3df0d0acf870.png)

**Comment by Huluti** [comment]
@bertob inital issue fixed on master with the valign property (thanks @A6GibKm !!).

without margins on the listbox it gives something weird with the border:
![image](https://user-images.githubusercontent.com/5782198/229496902-ee479169-a7e0-4371-804b-3eb70fc4d140.png)

**Comment by A6GibKm** [comment]
The usual container structure for a list box is 

```
  GtkScrolledWindow: (if this is an AdwWindow, the scrolled window might require vexpand=True)
    AdwClamp: (Here you would put margin-end, margin-start, etc)
        GtkListBox
```
probably here you have the margin or padding in the wrong place.

**Comment by Huluti** [comment]
![image](https://user-images.githubusercontent.com/5782198/229502298-d397d6d8-281d-4903-95f9-263c6f43b747.png)

@bertob is it the wanted behavior?

**Comment by bertob** [comment]
No, the padding all around the view seems to still be there (note the scrollbar not being on the window ege, and the cut-off content at the bottom).

**Comment by A6GibKm** [comment]
those would be the margins on `mainbox`.

**Comment by Huluti** [comment]
![image](https://user-images.githubusercontent.com/5782198/229564788-9de8b185-50ee-43d3-9641-84c6f3386bcd.png)

So much better! 😎 A big thank you to both of you!

**Comment by bertob** [comment]
Looks good to me now, thanks!
