### ISSUE TITLE
Allow to select folder with recursive scan for images

### ISSUE THREAD

**Issue by gavr123456789** [Huluti/Curtail#150]
The selection wanna get images, but I have big folder with many folders with images.   
For now I need to remember what folders of images was already processed(I'm using replace mode).  
![image](https://user-images.githubusercontent.com/30507409/230400460-1067084a-8961-4c84-a53d-7e03e38aeefb.png)

**Comment by gavr123456789** [comment]
Thanks!

**Comment by Huluti** [comment]
You can thank @rk234 :) I'll do a new release of Curtail as soon as possible. I just want to fix a last thing before.
