### ISSUE TITLE
Feature Request: Clarify Export Quality Settings

### ISSUE THREAD

**Issue by mrmatteastwood** [Huluti/Curtail#156]
The export quality settings are currently misleading. Users might misunderstand what the numbers mean:

![image](https://user-images.githubusercontent.com/22120259/230763535-83e5227f-263b-44bf-9fc1-93eb8a520ae3.png)

Does the "90" mean:

- 90% compression, leaving 10% quality?
- 90% quality, i.e., 10% compression?

A small "?" button explaining this would be useful.

**Comment by Huluti** [comment]
Fixed by a43aad1d24b8bb47af4feb56b69fb65a17a9755c.

**Comment by Huluti** [comment]
Fixed in 1.8.0 available on flathub :)

**Comment by mrmatteastwood** [comment]
Confirmed. Awesome, thanks!
