### ISSUE TITLE
1.7.0 creates 0 byte large PNG images

### ISSUE THREAD

**Issue by prokoudine** [Huluti/Curtail#160]
I have the latest release form flathub, 1.7.0. Instead of actually compressing PNG images, it creates a ton of 0 bytes large PNG files. Running it on Ubuntu 22.04, if that helps. What further info can I provide you to help troubleshooting this?

**Comment by Huluti** [comment]
Thanks for the report! Is it possible to share here an image that produces this problem?

**Comment by prokoudine** [comment]
> Thanks for the report! Is it possible to share here an image that produces this problem?

Regular PNG files created by GNOME's screenshot program.

**Comment by prokoudine** [comment]
Tested this on Ubuntu 23.04 and my own build from Git. Same issue on any images at all — PNG, JPEG, WebP.

**Comment by Huluti** [comment]
Can you copy what you have in the debug section in the about window please? (It should be something like this).

`Python: 3.10.6

Gtk: 4.10.3

Jpegoptim: 1.5.3

Oxipng: 8.0.0

pngquant: 2.18.0

Libwebp: 1.3.0

Scour: 0.38.2
`

**Comment by Huluti** [comment]
@prokoudine can you try to set a lower value for the lossless compression level (below 7)? it was an issue catched by @magicmyth
