### ISSUE TITLE
Started Building and Maintaining Snap Packages

### ISSUE THREAD

**Issue by CapeCrusader321** [Huluti/Curtail#164]
Hey there i have started building and maintaining the snap packages for curtail ;

<a href="https://snapcraft.io/curtail">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

Manifest/Source --> https://github.com/CapeCrusader321/curtail-snap

**Comment by Huluti** [comment]
Wow! Thank you very much for this contribution :) Will add it in the readme section!

**Comment by Huluti** [comment]
Added :)
