### ISSUE TITLE
Drag and Drop no longer works

### ISSUE THREAD

**Issue by Primokorn** [Huluti/Curtail#165]
Hello,
I normally use Curtail on a KDE Neon and the package is installed as a flatplak.
I tested today on another laptop with Arch Linux, Plasma 5.27.4 and via flathub. Same issue.

Curtail version: 1.7.0
I have to select the files manually (one by one) since drag and drop no longer works. [Demonstration](https://drive.proton.me/urls/AY059K708W#oc3eQpi0Df8N).

**Comment by Huluti** [comment]
Closing it for #166. Thanks for the report and the video!
