### ISSUE TITLE
Drag and drop folders doesn't work anymore.

### ISSUE THREAD

**Issue by Jacobthegr8** [Huluti/Curtail#166]
I am on version 1.7.0 and the drag and drop feature no longer works. It did in previous versions like 1.6.0 and 1.5.0.

**Comment by walrus543** [comment]
I tested the flatpak version 1.6.0 and 1.5.0 on EndeavourOS (Plasma as DE) and it didn't work either.
So I downgraded to 1.3.1-1 thanks to the `downgrade` package and it works now.
