### ISSUE TITLE
Open Image Or Open Folder

### ISSUE THREAD

**Issue by sbernard31** [Huluti/Curtail#197]
Ideally I would like to be able to `Open Image` or/and `Open Folder` from this screen. 

![Capture d’écran du 2023-11-22 14-34-27](https://github.com/Huluti/Curtail/assets/840294/40dc3c9b-5571-4159-9c19-2a440bbb50f6)

**Comment by Huluti** [comment]
I think that this is already possible.
You have several options:
- left icon of the headerbar for files
- drag & drop for folders & files
- folder option the in the menu

Reopen the issue if needed :)

**Comment by sbernard31** [comment]
It's possible that maybe you misunderstood me.

I would like to open the image with default image viewer  maybe by clicking on item in the list. 
and/or eventually open the folder containing the image in default file manager(e.g. nautilus) maybe by clicking on a "folder" icon which would be added near percent value. (or something like that)

Tell me If I not clear :slightly_smiling_face:

**Comment by Huluti** [comment]
Oh yes sorry, very clear now, sorry I mixed up a few things...

**Comment by Huluti** [comment]
Will be in next release :)
