### ISSUE TITLE
Format chooser screen

### ISSUE THREAD

**Issue by sbernard31** [Huluti/Curtail#198]
Instead of directly compress my files. 
I would like that **Curtail** propose me conversion with different format.
I could see saving space by proposed solution, then choose what I want. 

Ideally for lossy compression, an Image comparison screen could help to choose which compression to use.

**Comment by Huluti** [comment]
Curtail is not a conversion app but just a compression app.
Maybe you can use Curtail with this other app: https://apps.gnome.org/fr/Converter ?

**Comment by sbernard31** [comment]
ah OK. I was thinking that Curtail was an app to help people store their image in a smaller file as possible. 

From a user point of view, most of the time format is not really important.

**Comment by sbernard31** [comment]
>  Maybe you can use Curtail with this other app: https://apps.gnome.org/fr/Converter ?

Thx for the tips :pray:
