### ISSUE TITLE
Any Qt alternative ? Or at least a fix for that ugly Adwaita look ?

### ISSUE THREAD

**Issue by medmedin2014** [Huluti/Curtail#202]
On KDE Plasma, the app refuses to follow system theme, it looks alien because of that ugly and forced/embedded Adwaita theme.

Is Curtail only a GNOME app ? Because that cursed LibAdwaita library is specialized to create only GNOME apps to be locked to their ecosystem ! 

Why not use pure GTK4 widgets instead of LibAdwaita ?  So we can theme our app to look good and consistent with others.

```
Operating System: Manjaro Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.10-1-MANJARO (64-bit)
Graphics Platform: Wayland
```

![Screenshot_20240109_000431](https://github.com/Huluti/Curtail/assets/7027319/de2b48ca-87bc-4c28-bf0f-8e435bbcece8)

**Comment by Huluti** [comment]
Curtail is part of GNOME Circle and program so that's the reason we use LibAdwaita.
@bertob Do you know if on KDE a better theming is possible? Not sure to have the knowledge here...

**Comment by bertob** [comment]
Not sure I see the problem there, the app looks fine except for the weird colorful icons, but that seems like an issue with the environment rather than the app.

As for "following the system theme", that's always going to be an illusion unless you're using the platform toolkit or doing tons of work for a specific app/environment combination, see https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale

**Comment by medmedin2014** [comment]
It's only that cursed LibAdwaita that refuses to follow system theme, GTK3 and pure GTK4 apps follows it without any issue, I don't know why did you choose to use that LibAdwaita and lock this great application inside GNOME ecosystem, and not just adopt pure GTK4 widgets?

GNOME is now not the default Linux desktop, on [Arch based distros KDE is the most used one](https://pkgstats.archlinux.de/compare/packages#packages=budgie-desktop,cinnamon,gnome-shell,lxde-common,mate-panel,plasma-workspace,xfdesktop)

![Screenshot_20240412_131350](https://github.com/Huluti/Curtail/assets/7027319/f9ffb89a-e3b3-4686-9165-374dc9d436f6)

**Comment by Huluti** [comment]
I have chosen Libadwaita because Curtail is part of Gnome Circle and GTK 4 + Libadwaita are requirements.
Also, as Tobias said, the application works as expected.
I can understand your frustration, but nothing will change at this level.
Sorry.

**Comment by medmedin2014** [comment]
@Huluti Your arguments to tie your app inside GNOME are not convincing at all. Unless you change it to a GNOME app instead of a Linux app.
