### ISSUE TITLE
Dragging and dropping a folder with nested folder(s) shows unsupported format message

### ISSUE THREAD

**Issue by ARAKHN1D** [Huluti/Curtail#219]
Dragging and dropping a folder with folders inside of it displays them as unsupported file formats:
![nested_folders](https://github.com/Huluti/Curtail/assets/99846997/6bdd95fe-0d3c-488f-864a-07d4ba9b93b1)
It still compresses all the files inside the folder (including the nested ones), as shown here. This doesn't happen when bulk recursively compressing a directory, the nested folders just get ignored and only the compressed images are displayed. Maybe it would be better to also do this when dragging and dropping, at the very least for consistency.

Tested using Fedora Linux 39 and Curtail 1.9.1

**Comment by Huluti** [comment]
Good catch! it should be easy as the function already exists, I'll make a PR :)
