### ISSUE TITLE
Impossible to do batch lossy conversion from PNG to JPEG?

### ISSUE THREAD

**Issue by nekohayo** [Huluti/Curtail#233]
Today I wanted to convert a bunch of big lossless PNG images to lossy JPEG, but I was not able to with Curtail 1.10.0 from Flathub.

Whether I use the "Bulk Compress Directory" menu item action, or drag and drop multiple files at once onto the empty state window with the GtkSwitch widget set to "Lossy" mode, the resulting -min files are always PNGs; the app never prompts me for what output format I want, so I can never specify that I want JPEGs.

**Comment by Huluti** [comment]
Already indicated several times that Curtail is not a conversion tool. (https://github.com/Huluti/Curtail/issues/198 - https://github.com/Huluti/Curtail/issues/113).
