### ISSUE TITLE
I never remember why i did install Curtail in my Ubuntu Desktop, please add a more significant keyword/icon to this App.

### ISSUE THREAD

**Issue by hmvago** [Huluti/Curtail#237]
![image](https://github.com/user-attachments/assets/8fa0b317-a393-4ffc-bdc3-38fd6a64de42)

Thank you.

**Comment by Huluti** [comment]
Icon has been designed by @jimmac in 2020 and this is the first complaint, so no reason actually to dedicate time to this, sorry.

PR: https://github.com/Huluti/Curtail/pull/42
