### ISSUE TITLE
Consider changing name

### ISSUE THREAD

**Issue by hmvago** [Huluti/Curtail#241]
I've installed the application to my Ubuntu Desktop, I think It's going to be useful to me but for a while I'm not using it. Each time I see the app. icon and the "curtail" name I can't remember why I've installed it, what is for. Nothing (nor the name nor the icon) recalls me what this nice tool was meant to.

Please consider adding/changing something to make it self-explanatory.

Thank you.
Hernan

**Comment by Huluti** [comment]
https://github.com/Huluti/Curtail/issues/237
