### ISSUE TITLE
Indication that file compression was reverted

### ISSUE THREAD

**Issue by ARAKHN1D** [Huluti/Curtail#245]
Follow-up to #229. Maybe this could be a toast? Another thing to consider is, should this happen only when Curtail manually reverts the file, or also when the compressors skip the compression? The latter might be harder to figure out.

**Comment by Huluti** [comment]
I thought that maybe we could add the indication on each row? Instead of the percentage of reduction.
Maybe we would remove all the params that skip image if larger than original and rely on the system you added for all compressors?

**Comment by Huluti** [comment]
Or maybe instead of removing the skipping params, we could just check the old size against the new size and if new size is equal or superior we could write this text. "Skipped" is perfect for me.
What do you think?

**Comment by ARAKHN1D** [comment]
Checking the size would probably be better. I also think "Skipped" is a good indicator, but this is _technically_ incorrect for the system when Curtail is in overwrite mode. Since it overwrites the file first, that's technically reverting the file. Maybe the system could be updated to compress the temp file first, check if that's bigger or smaller, and then copy that file onto the original if it's smaller. This would allow for skipping the file in overwrite mode, but it would also mean successful compression would have one additional step. Would that be okay with you?

**Comment by Huluti** [comment]
It seems like a good idea for me!

**Comment by ARAKHN1D** [comment]
I'll work on it when I get the chance, and I'll ask you if I need help. Thanks :)
