### ISSUE TITLE
Curtail drops exports in /run/user/1000/doc folders

### ISSUE THREAD

**Issue by kekkoudesu** [Huluti/Curtail#248]
When I browse files and select a lot of files, the resulting export is dropped in random /run/user/1000/doc folders. It's really hard to then move these files back to the directory I want them to be.

Bulk-compress directory seems to drop the exports in the same folder, which is what I want.

Seems like a bug.

**Comment by Huluti** [comment]
You use the flatpak version? Can you try with the lastest release (1.11.1) and check if it's still happens?

**Comment by kekkoudesu** [comment]
I'm using the Flatpak vesrion. I'll try giving this another go soon.

**Comment by Huluti** [comment]
Same root cause as #185.
This happens when you select images outside the home folder (usb devices, ...).
