### ISSUE TITLE
Curtail 1.11.0 can no longer compress any file

### ISSUE THREAD

**Issue by archerallstars** [Huluti/Curtail#250]
I tried compressing PNG, JPEG, and WebP files without success. The app processes the files indefinitely.

The app worked well before version 1.11.0.

Debug info:

```
Python: 3.12.6

Gtk: 4.16.2

Jpegoptim: 1.5.5

Oxipng: 9.1.1

pngquant: 2.18.0

Libwebp: 1.4.0

Scour: 0.38.2
```

**Comment by Huluti** [comment]
Can reproduce indeed with filenames with spaces. Will try to publish a fix asap 
Thanks!

**Comment by ARAKHN1D** [comment]
Did some quick testing, and it looks like #249, which I opened for another issue, also fixes this one.

**Comment by Huluti** [comment]
Hmm that's strange that it fixes the issues... because the issues come from this commit: https://github.com/Huluti/Curtail/commit/6f0774874bfd51ff445e2f9965e87e14c676d53b

I'm working on an other way to fix the vulnerability and fix this current issue.

**Comment by ARAKHN1D** [comment]
Ah, it actually doesn't fix it. I didn't have that commit in my local repo. I'll look into some potential solutions too.

**Comment by Huluti** [comment]
My thought is that we should remove the quote function, remove shell=True from the subprocess.run call and so pass command params as array and not a string. But it requires a bit of work...

**Comment by ARAKHN1D** [comment]
Does Curtail already protect against shell injections since it puts double quotes around the filenames in the commands? I will admit I'm not very experienced in this area, so I'm not sure. Removing `shell=True` seems like it would definitely protect against this though, so that's probably the better option.

**Comment by ARAKHN1D** [comment]
Made a MR (#251) that'll hopefully solve both issues.

**Comment by Huluti** [comment]
Tested it successfully. Release in progress: https://github.com/flathub/com.github.huluti.Curtail/pull/17
Many thanks again for your precious help.
