### ISSUE TITLE
Files Saved in Gimp not compressing

### ISSUE THREAD

**Issue by monkusa** [Huluti/Curtail#252]
Hello Curtail Team,

My set up is as follows
-   -   -   -   -   -   -   -   -   -   -
Curtail version v1.11.0
GIMP version 2.10.30

PNG Settings (for saved files in GIMP) is:
Save background color
Save resolution
Save creation time
Save comment
Compression level 9
Save Exif data
Save XMP data
Save thumbnail
![image](https://github.com/user-attachments/assets/dfae532e-a1a1-47b3-8d7f-bb1be11127d9)
-   -   -   -   -   -   -   -   -   -   -

What I have found with the latest version of Curtail is that it is not compressing PNG files that I create in GIMP. It tends to stay in an endless loop - my curtail settings are default.
![image](https://github.com/user-attachments/assets/021a1a24-8a12-43e3-8eb0-c89c9252854a)

I have attached a sample PNG image that I created in GIMP for your reference and testing [Test Image.png].
![Test Image](https://github.com/user-attachments/assets/c5cdd48a-ecf1-4b49-9488-ed3cef02b3cc)

Thanks,
monkusa

**Comment by monkusa** [comment]
I just browsed through the other issues/tickets.

It seems that the problem is because the filename has a <space> in it. As soon as I renamed the file, the compression worked.

This issue/ticket that I have opened can be closed/ignored.
![Test_Image](https://github.com/user-attachments/assets/7766205a-e4fa-4403-aa0a-0edcf179483d)

**Comment by Huluti** [comment]
Thanks. Closed for #250
