### ISSUE TITLE
Read-only  translation 

### ISSUE THREAD

**Issue by yakushabb** [Huluti/Curtail#260]
> This module is read-only and no translation can be submitted. This is usually because the repository URL is not writable. Ask the platform coordinators to update the repository URL. 

Source: https://l10n.gnome.org/module/Curtail/

**Comment by Huluti** [comment]
Maybe fixed by #259 @rffontenelle ?

**Comment by rffontenelle** [comment]
@Huluti No, #259 is simply about regenerating de POT file and I confirmed that warning is now gone.

Damned Lies can't push translations to GitHub repositories unless you invite the push user used by that Damned Lies. [According to Guillaume](https://gitlab.gnome.org/Infrastructure/damned-lies/-/issues/574#note_2270388), that username is @gnomeinfra-github. My suggestion is: invite such username as a developer in your project and then comment in the linked issue requesting the invite to be accepted.

**Comment by Huluti** [comment]
User invited, thanks!

**Comment by averi** [comment]
Invitation accepted, thanks!

**Comment by yakushabb** [comment]
The error message is still there.

![image](https://github.com/user-attachments/assets/7eeb331d-590f-4bdd-bb39-7fc1e98a0c0f)

**Comment by Huluti** [comment]
Wonderful! Thanks all :)
