### ISSUE TITLE
Duplicated gschema description

### ISSUE THREAD

**Issue by rffontenelle** [Huluti/Curtail#261]
These two gschema entries have the same description. Is that intentional?

https://github.com/Huluti/Curtail/blob/b314ae903c803c4e87cbd031be0daff14f28002f/data/com.github.huluti.Curtail.gschema.xml#L14-L23

**Comment by Huluti** [comment]
Sounds like an error. Will take a look when going back from vacations tomorrow.

**Comment by rffontenelle** [comment]
Thanks. No rush 🏖️
