### ISSUE TITLE
Better name?

### ISSUE THREAD

**Issue by bertob** [Huluti/Curtail#39]
The current name is a bit weird, would you be interested in help with finding a better one?

This blog post has some tips for app naming: https://puri.sm/posts/librem-5-app-design-tutorial-naming-your-app

**Comment by Huluti** [comment]
Hi! I'm open to this suggestion. Do you have specials names in mind?

**Comment by jannuary** [comment]
Throwing some suggestions out:

- Condense
- Fold
- Shrink
- Squeeze 
- Subsample

**Comment by bertob** [comment]
I like most of @jannuary's suggestions (except for Subsample, which I don't get). Maybe you could add a `-er` suffix to make one of them more unique, e.g. `Condenser`. Another one could be `Compact` maybe.

**Comment by bertob** [comment]
Seeing as the app has already been accepted into Circle, it'd be good to get this resolved sooner rather than later.

**Comment by Huluti** [comment]
I like Condenser but it's a verb in French so I'll not be good for SEO. The others words are also just words and can't be "brands" in my mind.
What do you think of these ?
- Squify
- Desize
- Dimage

**Comment by bertob** [comment]
In terms of sound/feel, `Desize` sounds potentially viable, but an actual dictionary word would be better. We generally try to avoid made up constructs/combinations where possible.

**Comment by Huluti** [comment]
For me the problem with a dictionary word is that the software wouldn't be recognizable, right? This gives me the impression that it will be known only in the Gnome "world". Tell me if I miss something.

**Comment by bertob** [comment]
I mean, macOS/iOS apps do it all the time too, I don't think it's a practice exclusive to the GNOME world. Either way, for something like apps that you interact with all the time, a nice name that tells people what the app does in app stores or on the app grid is more important than a unique or SEO-friendly one.

**Comment by jimmac** [comment]
* **Quell**

**Comment by Huluti** [comment]
@bertob I understand your arguments. It's like you see this app as a base app. I would like to find a name which can be meaningful but which is not already used everywhere either.

@jimmac I like the name but I find it a bit violent by definition : put an end to (a rebellion or other disorder), typically by the use of force.)

I find these :
- Curtail
- Narrow
- Shaver

What's your opinion ?

**Comment by bertob** [comment]
Those three all sound good to me :+1:

**Comment by Huluti** [comment]
So I'll go with Curtail 🎉 Thank you all for your help I really appreciate it!

I'll start to rename the name wherever I can but do you know if flathub allows to change the name of an app? Do the current users will receive the new app when they will update it?

**Comment by Huluti** [comment]
The work is done and the app is buildable. So I just need to know if it possible to do the transition on flathub.

**Comment by Huluti** [comment]
Thank you all! The app with the new name and the new icon is available on Flathub: https://flathub.org/apps/details/com.github.huluti.Curtail

The current app has been marked EOL and it sould ask you to switch to the new app in the next few hours.
