### ISSUE TITLE
How do I run my build?

### ISSUE THREAD

**Issue by trst** [Huluti/Curtail#40]
Hello!

I'm trying to hack on ImCompressor and add a super simple feature (i.e., set the progressive encoding flat for jpegoptim and a toggle in the preference pane. I can add a PR if I end up getting that far :stuck_out_tongue_closed_eyes: ). I think I have everything ready to test, but I'm really new to desktop software and am a bit stuck with the build steps. I've managed to get meson to build and ninja to install but at a loss for the next steps to run the build.

Any pointers or any other documentation I ought to look at to help get me going again?

Thank you for your time and an app I use daily in my work for the web :smiling_face_with_three_hearts:

**Comment by Huluti** [comment]
Hi! Happy to know that my app is useful for daily users. I appreciate also that you're trying to contribute ;)

Personally I'm using [Gnome Builder](https://flathub.org/apps/details/org.gnome.Builder), you shoud try it I think!
It permits you to launch your build directly from its interface.

Say me if you can use it. In my memories building with meson and ninja manually install the soft directly in your desktop.

**Comment by trst** [comment]
I appreciate the tips. I'll start there and let you know how I get on :smile:

**Comment by Huluti** [comment]
In view of your PR I think I can close this ticket?
