### ISSUE TITLE
Problem installing via AUR (yay)

### ISSUE THREAD

**Issue by danielsanfr** [Huluti/Curtail#45]
Hello, thank you very much for developing this great application.

The "problem" I am having is that I am using Manjaro and I am trying to install your application via AUR using yay (Additionally I am using virtualenv).
I know that you do not support this installation method, but I believe the solution is quite simple, and maybe you can consider making the change.

Basically the problem is that during the build, the meson is taking the path of the python that points to virtualenv and not the python that is installed on my computer.
> _A more detailed explanation can be seen here https://github.com/rmarquis/pacaur/issues/400 and here https://github.com/Jguer/yay/issues/76._

So to solve the problem I have 2 suggestions.

1. Define the path in [src/curtail.in:1](https://github.com/Huluti/Curtail/blob/master/src/curtail.in#L1) which is the most common of python to be installed in most GNU/Linux distributions which is: `#!/usr/bin/python3`

or

2. Following the documentation for the [meson python module](https://mesonbuild.com/Python-module.html#find_installation), when using the `find_installation` command in [src/meson.build:15](https://github.com/Huluti/Curtail/blob/master/src/meson.build#L15), it should pass the `/usr/bin/python3` path, not the python name.

I hope you can consider my points, and thanks in advance for your time reading this issue.

**Comment by Huluti** [comment]
Thanks for using the app already! I think I understand the problem. Now for example if I take the first solution, according to you, it can solve this problem but at the same time do I not prevent the application from being used by other people if they do not have the same Python path? It's a real question, I don't know too much about packaging.

**Comment by Huluti** [comment]
I am closing this issue having no response at the moment. Do not hesitate to reopen it if you want to clarify.
