### ISSUE TITLE
A lot of "Compression not useful" windows pop up when compressing many files at once.

### ISSUE THREAD

**Issue by axredneck** [Huluti/Curtail#53]
It takes quite long to close them all. This reminds me about Windows 9x error messages.
Maybe add a checkbox to not show "Compression not useful" messages in Preferences?

**Comment by axredneck** [comment]
Edit: Curtail even crashes when there are too many of these popups

**Comment by Huluti** [comment]
Thank's for your report! I'm thinking about how to improve that and I keep you posted.

**Comment by Huluti** [comment]
Thank you for your report. It's fixed in master by removing this dialog and by allowing to have "negative" savings as it can be useful for progressive jpgs" for example.

**Comment by axredneck** [comment]
Now it spams "File already exists" - annoying too when compressing many files at once.

**Comment by Huluti** [comment]
@axredneck it's discussed in #54. Thank's!

**Comment by axredneck** [comment]
> @axredneck it's discussed in #54. Thank's!

#54 closed but this "File already exists" still annoys. Is it possible to make this popup optional?
