### ISSUE TITLE
1.1 release ❄️

### ISSUE THREAD

**Issue by Huluti** [Huluti/Curtail#55]
HI! A new release will be out soon with some new features and fixes.

### Added
- An option to progressive encode jpegs. Thank's to @trst.
- Add Russian translation.
- Add Slovak translation.
- Add Swedish translation.

### Changed
- Better handling of existing files.
- Better appdata summary.
- Update Spanish translation.

### Fixed
- Compress images with extensions in uppercase.
- Center preferences window header switcher. Thank's to @andrenete.
- Fix columns sorting. Thank's to @andrenete.
- Don't allow empty suffix (incorrect compression for JPEG). Thank's to @andrenete.

In order to have a good release I need some help of the translators to update their translations and ideally, it would be nice if some people test the new version from the source code to detect possible bugs (as there are some logic changes).

**TODO before 1.1 release:**
- [x] update translations
- [ ] test the soft

Thank's in advance! ❄️

**Comment by Finoway** [comment]
Hi !
If you need an french translation for the software do not hesitate to contact me on discord ``Finoway#2276`` I answer faster there otherwise you can ask me here but I would be slower to answer ;)
