### ISSUE TITLE
Guessing image type by extension is not reliable

### ISSUE THREAD

**Issue by akozlovskiy119** [Huluti/Curtail#64]
For example, JPEG image `picture.jpg` renamed to just `picture` or even `picture.png` is still JPEG image and should be treated as such. If I try to open this renamed file with GIMP, for example, it correctly detects the JPEG image type. Some other compressors like https://tinypng.com/ could handle this correctly too (it even changes the compressed file extension to the correct one).

Currently, Curtail fails to process such files or process them incorrectly, but it can do better by guessing file content type with Gio. Based on my experiments, if [`Gio.content_type_guess`](https://lazka.github.io/pgi-docs/Gio-2.0/functions.html#Gio.content_type_guess) is passed only data parameter (without filename), it will correctly detect JPEG type for described cases.

The downside of this approach, is that it requires reading some file contents even before compressing and may affect performance. Also, different platforms use different content type systems and comparing them should be handled with extra care. From [Gio docs](https://developer.gnome.org/gio/2.66/gio-GContentType.html):
> On UNIX it is a MIME type like text/plain or image/png. On Win32 it is an extension string like .doc, .txt or a perceived string like audio. Such strings can be looked up in the registry at HKEY_CLASSES_ROOT. On macOS it is a Uniform Type Identifier such as com.apple.application.

But it looks like there are functions in Gio for this — [`Gio.content_type_is_a`](https://lazka.github.io/pgi-docs/Gio-2.0/functions.html#Gio.content_type_is_a) and its wrapper [`Gio.content_type_is_mime_type`](https://lazka.github.io/pgi-docs/Gio-2.0/functions.html#Gio.content_type_is_mime_type).

**Comment by andrenete** [comment]
Simple script for testing: https://gist.github.com/andrenete/395277ba5ebbd6a3ccdf872ad64a1f37

**Comment by Huluti** [comment]
Thank you very much for you detailed explanations! I've tried a first approach based on your tests.
