### ISSUE TITLE
Nicer icon?

### ISSUE THREAD

**Issue by foreverxml** [Huluti/Curtail#72]
The current app icon for Curtail is this: 
![](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.github.huluti.Curtail.png)
And comparing it to a current Adwaita icon:
![](https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/com.rafaelmardojai.Blanket.png)
It seems a bit... old and skeuomorphic. Maybe we could develop a nicer icon for everyone? I love the app (in fact this is my only problem with the app!)

**Comment by foreverxml** [comment]
Update: New alpha modern icon design:
![Curtail modern logo](https://user-images.githubusercontent.com/52264162/113238549-3d6ff900-9266-11eb-9774-438c0b04e049.png)
Versus...
![Curtail old logo](https://camo.githubusercontent.com/d3aed3c5f6db9520ffca7b42a126827d1211374c1c762eb2588073cd63d2a678/68747470733a2f2f646c2e666c61746875622e6f72672f7265706f2f61707073747265616d2f7838365f36342f69636f6e732f313238783132382f636f6d2e6769746875622e68756c7574692e4375727461696c2e706e67)
It is alpha... remember that!

**Comment by Huluti** [comment]
Hi! Thank's for your work, but the icon has already been changed in December (#41, #42) by GNOME designers. For me, it fits perfectly in any GNOME environment (and non-GNOME envs too). The current icon is much more understandable than your mockup in my opinion. I'm sorry but I'll close this issue for now.
