### ISSUE TITLE
Manjaro KDE + drag-&-drop = Path Not Valid

### ISSUE THREAD

**Issue by justeepin** [Huluti/Curtail#77]
On two separate clean installs, using the Flatpak, AUR and official repo versions of Curtail on Manjaro KDE 21.0.5, whenever I drag-&-drop jpg files, I get an error message saying path not valid.  BUT on a clean install of KDE Neon it works fine.  Any ideas why that would be happening?

**Comment by Huluti** [comment]
This seems to be the same issue described here by @apandada1 : https://forum.manjaro.org/t/drag-and-drop-does-not-work-in-certain-gtk-apps-in-xfce/62574
