### ISSUE TITLE
Drag and Drop does not work in XFCE

### ISSUE THREAD

**Issue by apandada1** [Huluti/Curtail#78]
Previously reported in https://github.com/Huluti/Curtail/issues/77#issuecomment-848699379, but this may be different from #77, as here there is no error message in XFCE.

Drag and Drop works with [Cozy](https://github.com/geigi/cozy) in Manjaro XFCE. This is most likely the relevant source line https://github.com/geigi/cozy/blob/ad6832f221621cbb7f8beebe68949702e1dd92e1/cozy/ui/main_view.py#L634

**Comment by apandada1** [comment]
@Huluti  Can you release a new version so that these bug fixes go into distributions?

**Comment by Huluti** [comment]
@apandada1 I'll try to do a new release this evening 👍
