### ISSUE TITLE
WebP generation

### ISSUE THREAD

**Issue by prokoudine** [Huluti/Curtail#82]
It's probably well beyond what you intended Curtail for, but how do you feel about creating WebP files from PNG and JPEG? It would mess up the logics of the app a little, because the "overwrite existing files" option would become irrelevant though.

**Comment by olokelo** [comment]
I think I already [did that](https://github.com/Huluti/Curtail/pull/80#issue-661807399) a while ago but obviously it messes up the app.
This project is also image compressor, not converter so converting from PNG/JPEG to WEBP is beyond its functionality. Understandably the author wants the app to be coherent and simple to use.
I might be doing my fork of this project which will be image **converter** and resizer for GNU/Linux based on [Pillow](https://github.com/python-pillow/Pillow).

**Comment by Huluti** [comment]
Exactly! @olokelo the idea of a fork of this project is a good idea. I think that it could be very interesting to have two simple apps, an image compressor and an image converter. It respect the principle of GNU apps.

**Comment by Huluti** [comment]
I close the issue for now. @olokelo if you need some help to start the project, don't hesite to ping me 😀
