### ISSUE TITLE
Skipping already compressed files option does not work.

### ISSUE THREAD

**Issue by RDKRACZ** [Huluti/Curtail#95]
Clicking "Skip" here does not skip the files.
![image](https://user-images.githubusercontent.com/43277609/129480909-5f72ea0b-5b9f-4e49-8ebd-bcc3f7d943e3.png)

**Comment by Huluti** [comment]
Sorry for the late response. For me it works well, when I click on "Skip" the image it not compressed. Do you see the problem again?

**Comment by Huluti** [comment]
Closing this issue without answer. Please re-open it if needed.
